### ISSUE TITLE
[9.0] migration 8 to 9 : data in table delivery_carrier not merged correctly

### ISSUE THREAD

**Issue by AMhadhbi** [OCA/OpenUpgrade#1289]
Impacted versions:
9.0
Steps to reproduce:
the migration run perfect and without critical error. but when I checked the table delivery_carrier I found that the data into this table is changed and updated with other id. some deleted and other changed, I need these id in sale order and purchase order.

**database migrated v9 **
select id,name from delivery_carrier;

Current behavior:
**database migrated v9 **
![screen shot 2018-03-13 at 17 39 05](https://user-images.githubusercontent.com/10393083/37356252-cdb733b0-26e5-11e8-8d4a-8308e615e25f.png)
Expected behavior:
the data in version 9 should be the same as database version8.
**database v8**
![screen shot 2018-03-13 at 17 38 57](https://user-images.githubusercontent.com/10393083/37356285-e7969744-26e5-11e8-8a57-e88902173c0d.png)

Thanks

**Comment by AaronHForgeFlow** [comment]
Hi @AMhadhbi, did you pull the latest changes to your environment? This is supposed to be fixed here: https://github.com/OCA/OpenUpgrade/pull/1213

**Comment by AMhadhbi** [comment]
Hi @aheficent sure I worked with master in OpenUpgrade 9.0, but your latest changes with the method reassign_carrier_id(cr) not exist in master branch 9.0, have a look here [L48](https://github.com/OCA/OpenUpgrade/blob/9.0/addons/delivery/migrations/9.0.1.0/post-migration.py#L48). your pull not already merged in master branch 9.0? But here: #1213 was merged. @pedrobaeza could you please check this pull request. thanks[](url)

**Comment by pedrobaeza** [comment]
It was corrected in successive commits. See commit history:

https://github.com/OCA/OpenUpgrade/commits/9.0/addons/delivery/migrations/9.0.1.0

but everything should be OK now. Check commit logs to see reasons for the changes.

**Comment by AMhadhbi** [comment]
the OpenUpgrade branch v9 is up to date in my locally, after the migration database v9 the table delivery_carrier was changed, the id and the name. the problem still exist, I will try to add method reassign_carrier_id into the pull request #1213 to fix the issue.

**Comment by AaronHForgeFlow** [comment]
@AMhadhbi The ids are different because the table is recreated. This is not wrong. If you have some objects related to delivery.carrier you have to update those with a custom script. Here https://github.com/OCA/OpenUpgrade/pull/1213 it's done for sales and pickings, you can follow similar approach.

**Comment by pedrobaeza** [comment]
Closing as explanations are given.
